{{- if .Values.ingress.qaHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-app.fullname" . }}-qa
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.ingress.qaHost }}
      secretName: {{ include "simple-app.fullname" . }}-qa-tls
  rules:
    - host: {{ .Values.ingress.qaHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "simple-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
