name: Build, Push, and Deploy

on:
  push:
    branches:
      - master
      - main
      - '**'
  pull_request:
    branches:
      - master
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          pytest app/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            keko00/simple-app:latest
            keko00/simple-app:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Decode and write kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
        shell: bash



      - name: Deploy to QA or Prod via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: GITHUB_REF_NAME
          script: |
            cd simple-app/
            git pull
            if [[ "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "master" ]]; then
              echo "Deploying to prod namespace..."
              helm upgrade --install simple-app-prod ./charts/simple-app \
                --set image.tag=${{ github.sha }} \
                -f ./charts/simple-app/values-prod.yaml \
                --namespace prod \
                --create-namespace
            else
              echo "Deploying to qa namespace..."
              helm upgrade --install simple-app-qa ./charts/simple-app \
                --set image.tag=${{ github.sha }} \
                -f ./charts/simple-app/values-qa.yaml \
                --namespace qa \
                --create-namespace
            fi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
